version: "3"

services:
    db:
        image: postgres:11.7
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password
        volumes:
            - /var/lib/postgresql/data
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    django:
        build: ../WA-back-end
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ../WA-back-end/watergun_assassin:/usr/local/watergun-assassin-backend
        ports:
            - "8000:8000"
        restart: on-failure:5
        depends_on:
            - db
    frontend:
        build: ../WA-front-end
        command: bash -c "npm install -y && npm start"
        volumes:
            - ../WA-front-end:/usr/local/watergun-assassin-frontend
        ports:
            - "1234:3000"

volumes:
    node-modules:
